/* @/app/page.tsx */
import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";
/* [수정] Wallet 및 상속 메뉴용 Scale 아이콘 추가 */
import {
  KeyRound,
  Users,
  Building2,
  TrendingUp,
  BarChart3,
  Ticket,
  Scale,
  Bitcoin,
} from "lucide-react";

export const metadata = {
  title: "깐부 프로젝트",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div className={styles.logoContainer}>
          <Image
            className={styles.logo}
            src="/logo.png"
            alt="Next.js logo"
            width={500}
            height={500}
            priority
          />
        </div>

        <div className="text-center">
          <h1 className="text-4xl font-bold text-slate-900 dark:text-slate-100">
            깐부 자산 포트폴리오
          </h1>
          <p className="mt-2 text-lg text-slate-600 dark:text-slate-400">
            당신의 포트폴리오를 스마트하게 분석하세요
          </p>
        </div>

        <div className={styles.ctas}>
          <Link href="/kis-stock" className={styles.primary}>
            <TrendingUp className={styles.ctaIcon} />
            미국 주식
          </Link>
          <Link href="/k-stock" className={styles.primary}>
            <BarChart3 className={styles.ctaIcon} />
            한국 ETF
          </Link>
          <Link href="/binance" className={styles.primary}>
            <Bitcoin className={styles.ctaIcon} />
            바이낸스 선물
          </Link>
          <Link href="/lotto" className={styles.primary}>
            <Ticket className={styles.ctaIcon} />
            로또 추첨
          </Link>
          <Link href="/my-properties" className={styles.primary}>
            <Building2 className={styles.ctaIcon} />
            부동산
          </Link>
          <Link href="/inheritance" className={styles.primary}>
            <Scale className={styles.ctaIcon} />
            상속 케어
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href="/get-token" className={styles.footerLink}>
          <KeyRound className={styles.footerIcon} />
          토큰 발급
        </Link>
        <Link href="/api/friends" className={styles.footerLink} target="_blank">
          <Users className={styles.footerIcon} />
          친구 UUID 확인
        </Link>
      </footer>
    </div>
  );
}
